---
# Location where configuration files will be stored.
config_dir: '~'

# Pi-hole configuration.
pihole_enable: true
pihole_hostname: pi-hole
pihole_timezone: America/Chicago
pihole_password: "change-this-password"
