---
- hosts: pi
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yaml
        - config.yaml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yaml

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yaml

    - name: Set up Pi Hole.
      ansible.builtin.import_tasks: tasks/pi-hole.yaml
      when: pihole_enable

